# Generated by Django 4.0.4 on 2022-04-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='endereco',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='celular',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='nome',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='sobrenome',
            new_name='surname',
        ),
    ]
